---

- name: Import gpg key for Elastic repository
  rpm_key: key={{ elastic_gpg_key }}

- name: Add Elastic repository
  yum_repository:
    name: elastic
    description: Elastic repository
    baseurl: "{{ elastic_repo }}"
    gpgcheck: yes
    enabled: no

- name: Install Logstash
  yum:
    enablerepo: elastic
    name: filebeat
    update_cache: yes