---

- name: Install Filebeat
  import_tasks: install.yaml

- name: Create certificate
  include_role: name=create-certificate
  vars:
    certificate_installpath: /etc/filebeat
    certificate_owner: root
    certificate_group: root

- name: Configure Filebeat
  import_tasks: config.yaml
