---

- name: Enable openjdk11 on amazon linux
  command: amazon-linux-extras enable java-openjdk11

- name: Install Java
  yum: name=java-11-openjdk update_cache=yes

- name: Import gpg key for Elastic repository
  rpm_key: key={{ elastic_gpg_key }}

- name: Add Elastic repository
  yum_repository:
    name: elastic
    description: Elastic repository
    baseurl: "{{ elastic_repo }}"
    gpgcheck: yes
    enabled: no

- name: Install Logstash
  yum:
    enablerepo: elastic
    name: logstash
    update_cache: yes

- name: Download jmx_exporter
  get_url: url={{ jmx_exporter_url }} dest=/usr/share/logstash/jmx_exporter.jar owner=logstash group=logstash mode=0644
