---

- name: Install Logstash
  import_tasks: install.yaml

- name: Create certificate
  include_role: name=create-certificate
  vars:
    certificate_installpath: /etc/logstash
    certificate_owner: logstash
    certificate_group: logstash

- name: Configure Logstash
  import_tasks: config.yaml
