---

- block:

    - name: Wait a bit
      pause: minutes=2

    - name: Create default users
      shell: |
        /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b 2>&1 | \
          awk '
            BEGIN { 
              print "elasticsearch_passwords:"
            }
            /^PASSWORD / {
              print "  " $2 ": " $4
            }
          ' > /etc/elasticsearch/elasticsearch-users.yaml
      args:
        creates: /etc/elasticsearch/elasticsearch-users.yaml
        warn: no
      become: yes

    - name: Create local path for storing various external variables
      file: path=/home/ec2-user/.vars mode=0700 state=directory
      delegate_to: localhost
      connection: local

    - name: Copy user passwords 
      fetch: src=/etc/elasticsearch/elasticsearch-users.yaml dest=/home/ec2-user/.vars/ flat=yes fail_on_missing=yes
      become: yes

    - name: Reload external variables
      import_role: name=reload-vars

    - name: Define admin user
      uri:
        url: "{{ elasticsearch_url }}/_security/user/admin"
        body:
          password: admin01
          roles: ["superuser"]
          full_name: "Admin user"
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_passwords[elasticsearch_user] }}"
        force_basic_auth: yes
        method: PUT
        body_format: json
      register: uri_logstash_internal
      failed_when: uri_logstash_internal.status != 200

  run_once: yes