---

- block:

    - name: Create default users
      shell: |
        /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b 2>&1 | \
          awk '
            BEGIN { 
              print "elasticsearch_passwords:"
            }
            /^PASSWORD / {
              print "  " $2 ": " $4
            }
          ' > /etc/elasticsearch/elasticsearch-users.yaml
      args:
        creates: /etc/elasticsearch/elasticsearch-users.yaml
        warn: no
      become: yes
      become_user: elasticsearch

    - name: Create local path for storing various external variables
      file: path=/home/ec2-user/.vars mode=0700 state=directory
      become: no
      delegate_to: localhost
      connection: local

    - name: Copy user passwords 
      fetch: src=/etc/elasticsearch/elasticsearch-users.yaml dest=/home/ec2_user/.vars flat=yes fail_on_missing=yes

  run_once: yes