---

- hosts: localhost
  connection: local
  roles:
    - role: ca-authority

- hosts: elasticsearch
  become: yes
  roles:
    - role: common
    - role: elasticsearch

- hosts: elastic_coord
  roles:
    - role: elasticsearch-init
    