---

- hosts: localhost
  connection: local
  roles:
    - role: ca-authority
      tags: ['ca']
    - role: common
      tags: ['common']
      become: yes
    - role: controller-extras
      become: yes
    - role: cloudalchemy.node-exporter
      tags: ['monitoring']
    - role: cloudalchemy.blackbox-exporter
      tags: ['monitoring']
    - role: cloudalchemy.prometheus
      tags: ['monitoring','prometheus']
    - role: cloudalchemy.grafana
      tags: ['monitoring','grafana']
    - role: boards
      tags: [grafana, boards]
      become: yes

- hosts: elasticsearch
  become: yes
  roles:
    - role: common
      tags:
        - common
        - elasticsearch
    - role: elasticsearch
      tags: ['elasticsearch']
    - role: cloudalchemy.node-exporter
      tags: ['monitoring']

- hosts: elastic_coord
  roles:
    - role: elasticsearch-init
      tags: 
        - elasticsearch
        - elasticsearch-init

- hosts: localhost
  connection: local
  become: yes
  roles:
    - role: kibana
      tags: [kibana]

- hosts: elastic_logstash
  become: yes
  roles:
    - role: common
      tags:
        - common
        - logstash
    - role: logstash
      tags: ['logstash']
    - role: cloudalchemy.node-exporter
      tags: ['monitoring']
    
- hosts: fluentd_fluentd
  become: yes
  roles:
    - role: common
      tags:
        - common
        - fluentd
    - role: fluentd
      tags: ['fluentd']
    - role: cloudalchemy.node-exporter
      tags: ['monitoring']

- hosts: workload
  become: yes
  roles:
    - role: common
      tags:
        - common
        - workload
    - role: workload
      tags: ['workload']
    - role: cloudalchemy.node-exporter
      tags: ['monitoring']

- hosts: workload_logstash
  become: yes
  roles:
    - role: filebeat
      tags:
        - workload
        - filebeat

- hosts: workload_fluentd
  become: yes
  roles:
    - role: fluentbit
      tags:
        - workload
        - fluentbit