---

- hosts: localhost
  connection: local
  roles:
    - role: ca-authority
      tags: ['ca']
    - role: common
      tags: ['common']
      become: yes
    - role: controller-extras
      become: yes
    - role: cloudalchemy.blackbox-exporter
      tags: ['monitoring']
    - role: cloudalchemy.prometheus
      tags: ['monitoring']
    - role: cloudalchemy.grafana
      tags: ['monitoring']

- hosts: elasticsearch
  become: yes
  roles:
    - role: common
      tags:
        - common
        - elasticsearch
    - role: elasticsearch
      tags: ['elasticsearch']
    - role: cloudalchemy.node_exporter
      tags: ['monitoring']


- hosts: elastic_coord
  roles:
    - role: elasticsearch-init
      tags: 
        - elasticsearch
        - elasticsearch-init

- hosts: elastic_logstash
  become: yes
  roles:
    - role: common
      tags:
        - common
        - logstash
    - role: logstash
      tags: ['logstash']
    - role: cloudalchemy.node_exporter
      tags: ['monitoring']
    