---

- name: Import gpg key for TreasureData repository
  rpm_key: key={{ treasure_gpg_key }}

- name: Add TreasureData repository
  yum_repository:
    name: treasuredata
    description: TreasureData repository
    baseurl: "{{ treasure_repo }}"
    gpgcheck: yes
    enabled: no

- name: Install td-agent packages
  yum:
    enablerepo: treasuredata
    name: td-agent
    update_cache: yes

- name: Install plugins
  gem: 
    executable: /opt/td-agent/bin/fluent-gem
    name: "{{ item }}"
    user_install: no
  with_items:
    - fluent-plugin-elasticsearch
    - fluent-plugin-ping-message
    - fluent-plugin-prometheus