---
grafana_security:
  admin_user: admin
  admin_password: admin

grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true

grafana_dashboards:
  - dashboard_id: 11074
    revision_id: 4
    datasource: Prometheus
  - dashboard_id: 6287
    revision_id: 2
    datasource: Prometheus

prometheus_web_external_url: http://localhost:9090
prometheus_storage_retention: 7d

prometheus_targets:
  node:
    - targets:
        - master-1:9100
        - master-2:9100
        - master-3:9100
        - data-1:9100
        - data-2:9100
        - coord-1:9100
        - logstash:9100
        - fluentd:9100
        - workflow-logstash-1:9100
        - workflow-fluentd-1:9100
      labels:
        env: elk_efk

prometheus_scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:9090
  - job_name: grafana
    static_configs:
      - targets:
        - localhost:3000
  - job_name: node
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node.yml
  - job_name: java
    scrape_interval: 5s
    static_configs:
      - targets:
        - logstash:9101
  - job_name: fluentd
    scrape_interval: 5s
    static_configs:
      - targets:
        - fluentd:9101
  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

blackbox_exporter_web_listen_address: 127.0.0.1:9115
