---

- name: Install boards
  uri:
    url: "http://localhost:3000/api/dashboards/db"
    user: "{{ grafana_security.admin_user }}"
    password: "{{ grafana_security.admin_password }}"
    force_basic_auth: yes
    method: POST
    body_format: json
    body: >
      {
        "dashboard": {{ lookup('file', item ) }},
        "overwrite": true,
        "message": "Updated by ansible"
      }
  no_log: yes
  with_items:
    - my_board.json