---

- name: Provision hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Register CA
  copy: src={{ ca_cert }} dest=/etc/pki/ca-trust/source/anchors/ca.crt mode=0644
  register: copy_regca

- name: Update Certificate Authorities
  shell: |
    update-ca-trust force-enable
    update-ca-trust extract
  when: copy_regca.changed