---

- name: Provision hosts file
  template: src=hosts.j2 dest=/etc/hosts

- name: Register CA
  copy: src={{ ca_cert }} dest=/etc/pki/ca-trust/source/anchors/ca.crt mode=0644
  notify: 
    - Update Certificate Authorities

- name: Update ca trust, just in case that damn handler won't fire
  command: update-ca-trust