---

- name: Create private key
  openssl_privatekey:
    path: /etc/elasticsearch/node.key
    size: 2048
    type: RSA
    mode: "0600"

- name: Generate CSR
  openssl_csr:
    path: /var/tmp/node.csr
    privatekey_path: /etc/elasticsearch/node.key
    common_name: "{{ inventory_hostname_short }}"
    subject_alt_name: 'DNS:{{ inventory_hostname }},DNS:{{ ansible_default_ipv4.address }},IP:{{ ansible_default_ipv4.address }}'

- set_fact:
    __csr_path: "{{ ca_cert_store }}/csr/{{ inventory_hostname_short }}.csr"
    __cert_path: "{{ ca_cert_store }}/{{ inventory_hostname_short }}.cert"

- name: Fetch CSR
  fetch: src=/var/tmp/node.csr dest={{ __csr_path }} fail_on_missing=yes

- name: Create certificate
  openssl_cert:
    path: "{{ __cert_path }}"
    csr_path: "{{ __csr_path }}"
    ownca_path: "{{ ca_cert_store }}/ca.cert"
    ownca_privatekey_path: "{{ ca_cert_store }}/ca.key"
    provider: ownca
  delegate_to: localhost
  connection: local
  become: no

- name: Install certificate
  copy: src={{ __cert_path }} dest=/etc/elasticsearch/node.cert

- name: Install CA certificate
  copy: src={{ ca_cert_store }}/ca.cert dest=/etc/elasticsearch/ca.cert

- name: Generate fullchain pem file
  certificate_complete_chain:
    input_chain: "{{ lookup('file', __cert_path) }}"
    root_certificates: [ "{{ ca_cert_store }}/ca.cert" ]
  register: fullchain

- name: Install fullchain
  copy: 
    content: "{{ ''.join(fullchain.complete_chain) }}"
    dest: /etc/elasticsearch/fullchain.pem
