---

- name: Provision JVM options
  template: src=custom.options.j2 dest=/etc/elasticsearch/jvm.options.d/custom.options mode=0644
  notify: Restart Elasticsearch

- name: Provision Elasticsearch configuration
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0644
  notify: Restart Elasticsearch
  
- name: Set limits for elasticsearch user
  template: src=limits.conf.j2 dest=/etc/security/limits.d/elasticsearch.conf mode=0644

- name: Set limit for mmap counts
  sysctl: name=vm.max_map_count value=262144 

- name: Limit the number of tcp retransmissions
  sysctl: name=net.ipv4.tcp_retries2 value=5

- name: Create directory for unit overrides
  file: path=/etc/systemd/system/elasticsearch.service.d state=directory

- name: Install unit overrides for Elasticsearch.service
  template: src=override.conf.j2 dest=/etc/systemd/system/elasticsearch.service.d/override.conf mode=0644
  notify: Restart Elasticsearch

- name: Create default users
  shell: |
    touch /var/tmp/elasticsearch-users.yaml > /dev/null 2>&1
    chmod 0600 /var/tmp/elsaticsearch-users.yaml > /dev/null 2>&1
    /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b 2>&1 | \
      awk '/^PASSWORD / {print $2 ": " $4}' > /var/tmp/elasticsearch-users.yaml
  become: yes
  become_user: elasticsearch
  creates: /var/tmp/elasticsearch-users.yaml