---

- name: Install ElasticSearch
  import_tasks: install.yaml

- name: Set up storage
  import_tasks: storage.yaml
  when: elasticsearch_data_size is defined

- name: Create certificate
  include_role: name=create-certificate
  vars:
    certificate_installpath: /etc/elasticsearch
    certificate_owner: elasticsearch
    certificate_group: elasticsearch

- name: Configure Elasticsearch
  import_tasks: config.yaml
