---

- name: Install ElasticSearch
  import_tasks: install.yaml

- name: Set up storage
  import_tasks: storage.yaml
  when: elasticsearch_data_size is defined

- name: Configure Elasticsearch
  import_tasks: config.yaml
