---

- name: Download copy of soap-traffic-generator
  git: repo={{ generator_url }} dest=/home/ec2-user/soap-traffic-generator

- name: Install python3
  yum: name=python3

- name: Install PyPy packages
  pip: 
    executable: /usr/bin/pip3 
    name:
      - zeep
      - pyyaml
