---

- name: Install python3, git
  yum: 
    name: 
      - python3
      - git

- name: Install PyPy packages
  pip: 
    executable: /usr/bin/pip3 
    name:
      - zeep
      - pyyaml

- name: Download copy of soap-traffic-generator
  git: repo={{ generator_url }} dest=/home/ec2-user/soap-traffic-generator
  become: yes
  become_user: ec2-user
