---

- name: Install wildfly
  import_tasks: wildfly.yaml

- name: Install load generator script
  import_tasks: generator.yaml
  become: yes
  become_user: ec2_user

- name: Install webservice
  copy: src=wstest.war dest=/opt/wildfly/standalone/deployments/wstest.war owner=wildfly group=wildfly