---

- name: Enable openjdk11 on amazon linux
  command: amazon-linux-extras enable java-openjdk11

- name: Install Java
  yum: name=java-11-openjdk update_cache=yes

- name: Create wildfly group
  group: name=wildfly

- name: Create wildfly user
  user: name=wildfly group=wildfly shell=/sbin/nologin

- name: Install wildfly
  unarchive: src={{ wildfly_download_url }} remote_src=yes dest=/opt/ owner=wildfly group=wildfly

- name: Create symlink to Wildfly homedir
  file: src=/opt/wildfly-{{ wildfly_version }} dest=/opt/wildfly state=link
   
- name: Create service configuration dir
  file: path=/etc/wildfly state=directory owner=wildfly group=wilfly mode=0600
  notify: Restart wildfly

- name: Create service configuration file
  template: src=wildfly.conf.j2 dest=/etc/wildfly/wildfly.conf owner=wildfly group=wildfly
  notify: Restart wildfly

- name: Install SystemD unit
  template: src=wildfly.service.j2 dest=/etc/systemd/system/wildfly.service mode=0644
  notify: Restart wildfly