---
elastic_gpg_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
elastic_repo: https://artifacts.elastic.co/packages/7.x/yum

jmx_exporter_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.14.0/jmx_prometheus_javaagent-0.14.0.jar