---

- name: Install FluentD
  import_tasks: install.yaml

- name: Create certificate
  include_role: name=create-certificate
  vars:
    certificate_installpath: /etc/td-agent-bit
    certificate_owner: root
    certificate_group: root

- name: Configure FluentD
  import_tasks: config.yaml
